### ISSUE TITLE
CodeCakeBuilder broken - MSBuild gone from registry with latest VS2017

### ISSUE THREAD

**Issue by bcrosnier** [Invenietis/CK-Text#2] opened 2017-06-04 08:49 UTC
# Issue

After installing Visual Studio 2017 Pro, with .NET Desktop, Web and Core runtime and SDKs, `CodeCakeBuilder/Bootstrap.ps1` fails with the following error:

> Get-ItemProperty : Cannot find path 'HKLM:\software\Microsoft\MSBuild\ToolsVersions\14.0' because it does not exist.

# How to reproduce

1. Install Windows 10
2. Install the latest Visual Studio 2017 Pro, with .NET Desktop, Web and Core runtime and SDKs, as available on https://my.visualstudio.com
3. Open a PowerShell console in the solution directory and execute `./CodeCakeBuilder/Bootstrap.ps1`

# Workaround

`Bootstrap.ps1` can be edited by hand to point to the MSBuild file, which is `(Visual Studio installation path)\MSBuild\15.0\Bin\MSBuild.exe`

# Details

Upon further investigation, I found that, starting with version 15.1 (march 2017), **MSBuild no longer uses the registry to store its location**. Previous versions of MSBuild, which used to be at <https://www.microsoft.com/en-us/download/details.aspx?id=4815>, are also no longer available.

Documents detailing the change do exist at <https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0>, and state the following:

> MSBuild is now installed in a folder under each version of Visual Studio.
> You can also use the following PowerShell module to locate MSBuild: [vssetup.powershell](https://github.com/Microsoft/vssetup.powershell).
> MSBuildToolsPath no longer has a fixed location. By default, it is located in the MSBuild\15.0\Bin folder relative to the Visual Studio installation location, but the Visual Studio installation location can be changed at install time.
> ToolsVersion values are no longer set in the registry.

Appveyor should continue to work until the build image is refreshed.

Visual Studio installations from before the update should continue to work, as the now-obsolete MSBuild and registry key are not removed when updating.

Obviously, this affects all CodeCakeBuilder-built packages, not just CK-Text.

**Comment by olivier-spinelli** [comment] 2017-06-04 14:26
Good catch ??
Did you alter the bootrap.ps1 script of  CK-Text to use the new configuration ?

Envoyé de mon téléphone Windows 10

De : Benjamin Crosnier<mailto:notifications@github.com>
Envoyé le :dimanche 4 juin 2017 10:50
À : Invenietis/CK-Text<mailto:CK-Text@noreply.github.com>
Cc : Subscribed<mailto:subscribed@noreply.github.com>
Objet :[Invenietis/CK-Text] CodeCakeBuilder broken - MSBuild gone from registry with latest VS2017 (#2)

Issue

After installing Visual Studio 2017 Pro, with .NET Desktop, Web and Core runtime and SDKs, CodeCakeBuilder/Bootstrap.ps1 fails with the following error:

Get-ItemProperty : Cannot find path 'HKLM:\software\Microsoft\MSBuild\ToolsVersions\14.0' because it does not exist.

How to reproduce

  1.  Install Windows 10
  2.  Install the latest Visual Studio 2017 Pro, with .NET Desktop, Web and Core runtime and SDKs, as available on https://my.visualstudio.com
  3.  Open a PowerShell console in the solution directory and execute ./CodeCakeBuilder/Bootstrap.ps1

Workaround

Bootstrap.ps1 can be edited by hand to point to the MSBuild file, which is (Visual Studio installation path)\MSBuild\15.0\Bin\MSBuild.exe

Details

Upon further investigation, I found that, starting with version 15.1 (march 2017), MSBuild no longer uses the registry to store its location. Previous versions of MSBuild, which used to be at https://www.microsoft.com/en-us/download/details.aspx?id=4815, are also no longer available.

Documents detailing the change do exist at https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0, and state the following:

MSBuild is now installed in a folder under each version of Visual Studio.
You can also use the following PowerShell module to locate MSBuild: vssetup.powershell<https://github.com/Microsoft/vssetup.powershell>.
MSBuildToolsPath no longer has a fixed location. By default, it is located in the MSBuild\15.0\Bin folder relative to the Visual Studio installation location, but the Visual Studio installation location can be changed at install time.
ToolsVersion values are no longer set in the registry.

Appveyor should continue to work until the build image is refreshed.

Visual Studio installations from before the update should continue to work, as the now-obsolete MSBuild and registry key are not removed when updating.

Obviously, this affects all CodeCakeBuilder-built packages, not just CK-Text.

**Comment by Kuinox** [comment] 2020-05-24 19:08
I guess we can close this now ? @bcrosnier

**Closed** 2020-05-25 07:43 UTC
